cheetah: Drop digitalkey timesync
* crashes a lot

07-03 19:53:40.560 16871 16871 E AndroidRuntime: FATAL EXCEPTION: main
07-03 19:53:40.560 16871 16871 E AndroidRuntime: Process: com.google.pixel.digitalkey.timesync, PID: 16871
07-03 19:53:40.560 16871 16871 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: [Lorg/carconnectivity/android/digitalkey/timesync/Version;
07-03 19:53:40.560 16871 16871 E AndroidRuntime: 	at com.google.pixel.digitalkey.timesync.CccDkTimeSyncService.<clinit>(CccDkTimeSyncService.java:49)
07-03 19:53:40.560 16871 16871 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
07-03 19:53:40.560 16871 16871 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
07-03 19:53:40.560 16871 16871 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4884)
07-03 19:53:40.560 16871 16871 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
07-03 19:53:40.560 16871 16871 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2407)
07-03 19:53:40.560 16871 16871 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
07-03 19:53:40.560 16871 16871 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
07-03 19:53:40.560 16871 16871 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
07-03 19:53:40.560 16871 16871 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8594)
07-03 19:53:40.560 16871 16871 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-03 19:53:40.560 16871 16871 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
07-03 19:53:40.560 16871 16871 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
07-03 19:53:40.560 16871 16871 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: org.carconnectivity.android.digitalkey.timesync.Version

Signed-off-by: minaripenguin <minaripenguin@users.noreply.github.com>